### ISSUE TITLE
What's the point of the 'link' structs in 'struct region' in the reference tm.c?

### ISSUE THREAD

**Issue by zaitoichi** [LPD-EPFL/CS453-2018-project#12]
If all they do is point to the next and previous links? Shouldn't they be pointing to prev/next region objects instead?

**Comment by srlt** [comment]
There is only one _region_ instantiated by `tm_create`, and `tm_alloc`/`tm_free` instantiate/destroy _segments_ of shared memory for that region.
Because the alignment and size of a segment are only known at runtime, no `struct` has been specified for them, which I understand may render the code less readable.

So to answer your questions:
  1. yes they only point to the next and previous links (which can both be the link itself); you can see this kind of list as a "ring": keep following the next elements from a given link will eventually lead you back to the link you started with. 
  2. a link needs not point to the prev/next  _segment_ objects, pointing to the associated links in the adjacent _segment_ structure is enough (see below); and here by construction a pointer to a _segment_ is also a pointer to its only _link_ structure, so no need to use `objectof`.

In general, for the link to point to other links is a completely valid and versatile construct (e.g. widely used in the Linux kernel, follow https://elixir.bootlin.com/linux/latest/ident/list_head, and see `struct list_head` and `include/linux/list.h`). If you are interested, I am open to debate about design during the project session/office hours; maybe you'll change my mind.

If you think you actually found a bug, first let me say this is great and thanks for contributing (and feel absolutely free to reopen), but please try to make it a bit clearer (and if you can _highlight_ the bug, e.g. like in issues #9 and #10, this would be amazing).
