### ISSUE TITLE
Correct usage of std::align()?

### ISSUE THREAD

**Issue by zaitoichi** [LPD-EPFL/CS453-2018-project#13]
Given a region struct similar to that in the reference, is this the correct usage in `tm_create()`:
`std::align(align_alloc, size, region->start, region->size)` ?

**Comment by srlt** [comment]
I would be inclined to say this is yours to tell 😃, as this issue is not related to the content of the course (e.g. C++11 atomic and memory model) but general knowledge of C++.

According to https://en.cppreference.com/w/cpp/memory/align, you should check the return value of `std::align`, which you do not seem to do here.
So my answer would be no, this is not the correct usage.

It is hard to say more with only one line of code and no context (even if you are apparently using the names from the reference implementation). I think you'll understand I would rather discuss this kind of issue with your code, during the project sessions/office hours.
And again, please bear in mind that as a master student you should be able to solve this kind of issue in full autonomy (which I am sure you already did by the time I answered).
