### ISSUE TITLE
What does memset() do?

### ISSUE THREAD

**Issue by zaitoichi** [LPD-EPFL/CS453-2018-project#14]
When used in `tm_create()`, `memset(region->start, 0, size);` is called. How is it setting the memory allocated at `start` from N to C if all you're passing is a `void*`?

**Comment by zablotchi** [comment]
I'm not sure what you bean by "from N to C".

According to the [manual](https://linux.die.net/man/3/memset), `memset(region->start, 0, size)` simply sets to `0` the first `size` bytes of the memory area pointed to by `region->start`. It doesn't care what type(s) are stored in that memory area, which is why it takes `void*`.
