### ISSUE TITLE
Consistency check

### ISSUE THREAD

**Issue by vincenzobaz** [LPD-EPFL/CS453-2018-project#16]
If I replace my `tm_write` function by a single `return true` statement, the grading.cpp does not complain about inconsistencies even if values are never written.
Is this behavior intended?
If it is, what kind of *inconsistencies* does `grading.cpp` check?

```c
bool tm_write(shared_t shared, tx_t tx, void const* source, size_t size, void* target) {
    return true;
}
```
gives:
```
⎧ #worker threads:     4
⎪ #TX per worker:      100000
⎪ #repetitions:        7
⎪ Initial #accounts:   128
⎪ Expected #accounts:  4096
⎪ Initial balance:     100
⎪ Long TX probability: 0.5
⎪ Allocation TX prob.: 0
⎪ Slow trigger factor: 2
⎪ Clock resolution:    1 ns
⎩ Seed value:          453
⎧ Evaluating '../reference.so' (reference)...
⎪ Total user execution time: 600.168 ms
⎩ Average TX execution time: 1500.42 ns
⎧ Evaluating '../249733.so'...
⎪ Total user execution time: 200.057 ms -> 2.99999 speedup
⎩ Average TX execution time: 500.142 ns
```

**Comment by srlt** [comment]
If you don't modify the shared memory,
then you cannot introduce any inconsistency (since the initial state of the shared memory is consistent).
So yes, this is one expected behavior,
though your TM implementation would then be **incorrect** (transactions are not serializable).

What is a consistent state depends on the _semantic_ of the data.
Here the data basically represents _n_ bank accounts which shares _n×m_ "units of money".
So one instance of inconsistent state would be when the sum of all bank accounts does not equal _n×m_.
This is the kind of inconsistency `grading` checks.
